name: python

on: [push, pull_request]

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check code
      run: |
        pip3 install -r requirements.txt
        pip3 install flake8 pylint
        echo "RUNNING PYLINT PY3K CHECK"
        pylint --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" sweep_PR.py
        echo ""
        echo "RUNNING FLAKE8 CHECK"
        flake8 sweep_PR.py
